# Generated by Django 2.1.7 on 2019-02-27 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=400)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('ACCEPTED', 'ACCEPTED'), ('COMPLETED', 'COMPLETED'), ('REJECTED', 'REJECTED')], default='INTERESTED', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_type', models.CharField(choices=[('one-way', 'one-way'), ('round', 'round')], max_length=7)),
                ('origin_airport', models.CharField(max_length=25)),
                ('destination_airport', models.CharField(max_length=25)),
                ('departure_date', models.DateTimeField()),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('departure_airlines', models.CharField(max_length=30)),
                ('return_airlines', models.CharField(blank=True, max_length=30, null=True)),
                ('adults', models.IntegerField(default=0)),
                ('childrens', models.IntegerField(default=0)),
                ('infants', models.IntegerField(default=0, help_text='Age below 2 Years')),
                ('traveler_type', models.CharField(choices=[('self', 'self'), ('parents', 'parents'), ('spouse', 'spouse'), ('other', 'other')], max_length=15)),
                ('sponsorship', models.CharField(choices=[('one-third', 'one-third'), ('half', 'half'), ('full', 'full'), ('other', 'other')], max_length=15)),
                ('sponsorship_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('ACCEPTED', 'ACCEPTED'), ('COMPLETED', 'COMPLETED'), ('REJECTED', 'REJECTED')], default='ACTIVE', max_length=10)),
                ('request_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Traveller')),
            ],
        ),
        migrations.AddField(
            model_name='companion',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companion.Request'),
        ),
        migrations.AddField(
            model_name='companion',
            name='requestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Traveller'),
        ),
    ]
