# Generated by Django 2.1.7 on 2019-03-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companion', '0002_auto_20190308_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='children',
        ),
        migrations.RemoveField(
            model_name='request',
            name='infants',
        ),
        migrations.AlterField(
            model_name='request',
            name='destination_airport',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='request',
            name='origin_airport',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='request',
            name='traveler_type',
            field=models.CharField(choices=[('self', 'self'), ('parents', 'parents'), ('spouse', 'spouse'), ('kids', 'kids'), ('other', 'other')], max_length=15),
        ),
    ]
