# Generated by Django 2.1.7 on 2019-03-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companion', '0003_auto_20190327_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='sponsorship',
            field=models.CharField(choices=[('none', 'none'), ('one-third', 'one-third'), ('half', 'half'), ('full', 'full'), ('other', 'other')], max_length=15),
        ),
    ]
