# Generated by Django 2.1.7 on 2019-04-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companion', '0006_auto_20190408_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='departure_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
