# Generated by Django 2.1.7 on 2019-04-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveller',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traveller',
            name='nationality',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
