# Generated by Django 2.1.7 on 2019-04-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190402_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveller',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
