# Generated by Django 2.1.7 on 2019-04-16 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_traveller_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='CognitoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_token', models.CharField(max_length=2500)),
                ('access_token', models.CharField(max_length=2500)),
                ('refresh_token', models.CharField(max_length=2500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
